[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "2gv7MifddJqY2dyLUqmvSAGuMrKvxB65QDA5gW6PqFNU"

[programs.devnet]
escrow = "2gv7MifddJqY2dyLUqmvSAGuMrKvxB65QDA5gW6PqFNU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
