export function AppFooter() {
  return (
    <footer className="text-center p-2 bg-card/50 text-xs">
      {/* Removed 'Generated by' text */}
      {/* Removed create-solana-dapp link */}
    </footer>
  )
}
